/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "inverse-surface": "#e8edf2",
        "surface-bright": "#1a212b",
        "surface": "#080e17",
        "secondary-container": "#1e293b",
        "on-tertiary-container": "#5fa98c",
        "tertiary-fixed-dim": "#8bd6b6",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-surface": "#e8edf2",
        "on-secondary-container": "#94a3b8",
        "on-background": "#e8edf2",
        "outline-variant": "#334155",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#94a3b8",
        "secondary-fixed": "#1e293b",
        "surface-container-highest": "#334155",
        "on-primary-container": "#60a5fa",
        "primary-fixed": "#1e3a8a",
        "outline": "#64748b",
        "error": "#ef4444",
        "tertiary": "#14f195",
        "secondary-fixed-dim": "#475569",
        "surface-container-lowest": "#05090f",
        "error-container": "#7f1d1d",
        "primary-fixed-dim": "#1e40af",
        "on-tertiary-fixed-variant": "#10b981",
        "primary": "#3b82f6",
        "on-primary-fixed-variant": "#93c5fd",
        "secondary": "#64748b",
        "on-primary-fixed": "#bfdbfe",
        "background": "#080e17",
        "surface-variant": "#1e293b",
        "surface-dim": "#0a0f1a",
        "primary-container": "#172554",
        "on-tertiary-fixed": "#34d399",
        "on-secondary-fixed": "#cbd5e1",
        "surface-container": "#0f172a",
        "inverse-primary": "#1e3a8a",
        "tertiary-fixed": "#6ee7b7",
        "on-surface-variant": "#94a3b8",
        "inverse-on-surface": "#080e17",
        "tertiary-container": "#064e3b",
        "surface-container-high": "#1e293b",
        "surface-tint": "#3b82f6",
        "surface-container-low": "#0b121e",
        "on-error-container": "#fca5a5"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "sans": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
