/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "inverse-surface": "#e8edf2",
        "surface-bright": "#1a212b",
        "surface": "#080e17",
        "secondary-container": "#1e293b",
        "on-tertiary-container": "#5fa98c",
        "tertiary-fixed-dim": "#8bd6b6",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-surface": "#e8edf2",
        "on-secondary-container": "#94a3b8",
        "on-background": "#e8edf2",
        "outline-variant": "#334155",
        "on-primary": "#030712",
        "on-secondary-fixed-variant": "#94a3b8",
        "secondary-fixed": "#1e293b",
        "surface-container-highest": "#1f2937",
        "on-primary-container": "#60a5fa",
        "primary-fixed": "#1e3a8a",
        "outline": "#64748b",
        "error": "#ef4444",
        "tertiary": "#14f195",
        "secondary-fixed-dim": "#475569",
        "surface-container-lowest": "#030712",
        "error-container": "#7f1d1d",
        "primary-fixed-dim": "#1e40af",
        "on-tertiary-fixed-variant": "#10b981",
        "primary": "#00f0ff",
        "on-primary-fixed-variant": "#93c5fd",
        "secondary": "#a855f7",
        "on-primary-fixed": "#bfdbfe",
        "background": "#02040a",
        "surface-variant": "#111827",
        "surface-dim": "#050505",
        "primary-container": "#083344",
        "on-tertiary-fixed": "#34d399",
        "on-secondary-fixed": "#cbd5e1",
        "surface-container": "#0f172a",
        "inverse-primary": "#1e3a8a",
        "tertiary-fixed": "#6ee7b7",
        "on-surface-variant": "#94a3b8",
        "inverse-on-surface": "#080e17",
        "tertiary-container": "#064e3b",
        "surface-container-high": "#111827",
        "surface-tint": "#00f0ff",
        "surface-container-low": "#090d16",
        "on-error-container": "#fca5a5"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem"
      },
      fontFamily: {
        "headline": ["Outfit", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"],
        "sans": ["Plus Jakarta Sans", "sans-serif"]
      },
      backgroundImage: {
        'glass-gradient': 'linear-gradient(135deg, rgba(255, 255, 255, 0.08) 0%, rgba(255, 255, 255, 0.02) 100%)',
        'glass-glow': 'linear-gradient(135deg, rgba(0, 240, 255, 0.15) 0%, rgba(168, 85, 247, 0.15) 100%)',
        'radial-glow': 'radial-gradient(circle at center, rgba(0, 240, 255, 0.15) 0%, transparent 70%)',
        'purple-glow': 'radial-gradient(circle at center, rgba(168, 85, 247, 0.15) 0%, transparent 70%)',
      }
    },
  },
  plugins: [],
}
