import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

/**
 * Pabandi Smart Contract Deploy Script
 * ─────────────────────────────────────
 * Deploys in order:
 *   1. PABToken          — ERC-20 PAB utility token
 *   2. PabandiEscrow     — Booking deposit escrow
 *   3. PabandiSoulbound  — Soulbound NFT badge system
 *
 * Writes deployed addresses to:
 *   ../server/.env.contracts  (auto-loaded by server)
 *   ./deployments/<network>.json
 *
 * Run:
 *   npx hardhat run scripts/deploy.ts --network bscTestnet
 *   npx hardhat run scripts/deploy.ts --network bscMainnet
 */
async function main() {
  const [deployer] = await ethers.getSigners();
  const network = (await ethers.provider.getNetwork()).name;
  const chainId = (await ethers.provider.getNetwork()).chainId;

  console.log("\n🚀  Pabandi Contract Deployment");
  console.log("══════════════════════════════════════");
  console.log(`Network:   ${network} (chainId: ${chainId})`);
  console.log(`Deployer:  ${deployer.address}`);
  console.log(`Balance:   ${ethers.formatEther(await ethers.provider.getBalance(deployer.address))} BNB\n`);

  // ── Addresses ──────────────────────────────────────────────────────────────
  // Admin = deployer initially; transfer to multisig post-deployment
  const admin    = deployer.address;
  const minter   = process.env.MINTER_ADDRESS   || deployer.address;
  const relayer  = process.env.RELAYER_ADDRESS  || deployer.address;
  const treasury = process.env.TREASURY_ADDRESS || deployer.address;

  console.log(`Admin:     ${admin}`);
  console.log(`Minter:    ${minter}`);
  console.log(`Relayer:   ${relayer}`);
  console.log(`Treasury:  ${treasury}\n`);

  // ── 1. PABToken ────────────────────────────────────────────────────────────
  console.log("📄  Deploying PABToken...");
  const PABToken = await ethers.getContractFactory("PABToken");
  const pabToken = await PABToken.deploy(admin, minter);
  await pabToken.waitForDeployment();
  const pabTokenAddress = await pabToken.getAddress();
  console.log(`   ✅  PABToken deployed at: ${pabTokenAddress}`);

  // ── 2. PabandiEscrow ───────────────────────────────────────────────────────
  console.log("\n📄  Deploying PabandiEscrow...");
  const PabandiEscrow = await ethers.getContractFactory("PabandiEscrow");
  const escrow = await PabandiEscrow.deploy(admin, relayer, treasury);
  await escrow.waitForDeployment();
  const escrowAddress = await escrow.getAddress();
  console.log(`   ✅  PabandiEscrow deployed at: ${escrowAddress}`);

  // ── 3. PabandiSoulbound ────────────────────────────────────────────────────
  console.log("\n📄  Deploying PabandiSoulbound...");
  const PabandiSoulbound = await ethers.getContractFactory("PabandiSoulbound");
  const soulbound = await PabandiSoulbound.deploy(admin, minter);
  await soulbound.waitForDeployment();
  const soulboundAddress = await soulbound.getAddress();
  console.log(`   ✅  PabandiSoulbound deployed at: ${soulboundAddress}`);

  // ── Save addresses ─────────────────────────────────────────────────────────
  const deployment = {
    network,
    chainId: chainId.toString(),
    deployedAt: new Date().toISOString(),
    deployer: deployer.address,
    contracts: {
      PABToken:         pabTokenAddress,
      PabandiEscrow:    escrowAddress,
      PabandiSoulbound: soulboundAddress,
    },
  };

  const deploymentsDir = path.join(__dirname, "../deployments");
  if (!fs.existsSync(deploymentsDir)) fs.mkdirSync(deploymentsDir, { recursive: true });
  
  const deploymentFile = path.join(deploymentsDir, `${network}.json`);
  fs.writeFileSync(deploymentFile, JSON.stringify(deployment, null, 2));
  console.log(`\n💾  Deployment record saved to: ${deploymentFile}`);

  // Write to server .env.contracts for easy server integration
  const envContent = [
    `# Auto-generated by deploy.ts — ${new Date().toISOString()}`,
    `# Network: ${network} (chainId: ${chainId})`,
    `PAB_TOKEN_ADDRESS=${pabTokenAddress}`,
    `ESCROW_CONTRACT_ADDRESS=${escrowAddress}`,
    `SOULBOUND_CONTRACT_ADDRESS=${soulboundAddress}`,
    `BLOCKCHAIN_NETWORK=${network}`,
    `BLOCKCHAIN_CHAIN_ID=${chainId}`,
  ].join("\n");

  const envFile = path.join(__dirname, "../../server/.env.contracts");
  fs.writeFileSync(envFile, envContent);
  console.log(`💾  Contract addresses saved to: ${envFile}`);

  // ── Summary ────────────────────────────────────────────────────────────────
  console.log("\n══════════════════════════════════════");
  console.log("🎉  Deployment complete!\n");
  console.log(`   PABToken:         ${pabTokenAddress}`);
  console.log(`   PabandiEscrow:    ${escrowAddress}`);
  console.log(`   PabandiSoulbound: ${soulboundAddress}`);
  console.log("\n📋  Next steps:");
  console.log("   1. Verify on BscScan: npx hardhat verify --network bscTestnet <address> <args>");
  console.log("   2. Transfer MINTER_ROLE to server relayer wallet");
  console.log("   3. Transfer DEFAULT_ADMIN_ROLE to multisig");
  console.log("   4. Add PAB_TOKEN_ADDRESS etc. to server/.env\n");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
