import { Routes, Route, Navigate } from 'react-router-dom';
import { useAuthStore } from './store/authStore';
import Layout from './components/Layout';
import HomePage from './pages/HomePage';
import AuthPage from './pages/AuthPage';
import AuthCallbackPage from './pages/AuthCallbackPage';
import BusinessDashboard from './pages/BusinessDashboard';
import BusinessRegister from './pages/BusinessRegister';
import ReservationsPage from './pages/ReservationsPage';
import NewReservationPage from './pages/NewReservationPage';
import { CheckoutSessionPage } from './pages/CheckoutSessionPage';
import CheckoutSuccessPage from './pages/CheckoutSuccessPage';
import BookingPage from './pages/BookingPage';
import ShortLinkBookingPage from './pages/ShortLinkBookingPage';
import BusinessProfilePage from './pages/BusinessProfilePage';
import BusinessCrmPage from './pages/BusinessCrmPage';
import WalletDashboard from './pages/WalletDashboard';
import AdminPanel from './pages/AdminPanel';
import BusinessJoinPage from './pages/BusinessJoinPage';
import BusinessActivationPage from './pages/BusinessActivationPage';
import BusinessModelPage from './pages/BusinessModelPage';
import TechnologyPage from './pages/TechnologyPage';
import ContactPage from './pages/ContactPage';
import BusinessSettingsPage from './pages/BusinessSettingsPage';
import ForgotPasswordPage from './pages/ForgotPasswordPage';
import ResetPasswordPage from './pages/ResetPasswordPage';
import ProfilePage from './pages/ProfilePage';
import DietaryPassportPage from './pages/DietaryPassportPage';
import DeveloperPortalPage from './pages/DeveloperPortalPage';
import TrustPage from './pages/TrustPage';
import PrivacyPolicyPage from './pages/PrivacyPolicyPage';
import TermsOfServicePage from './pages/TermsOfServicePage';
import TapPayPage from './pages/TapPayPage';
import UniversalCheckoutPage from './pages/UniversalCheckoutPage';
import { WaitlistPage } from './pages/WaitlistPage';
import Web3Page from './pages/Web3Page';
import HospitalityPage from './pages/HospitalityPage';
import AirdropPage from './pages/AirdropPage';
import CityLandingPage from './pages/CityLandingPage';
import LiveSellCustomerPage from './pages/LiveSellCustomerPage';
import LiveSellingPage from './pages/LiveSellingPage';
import FreelancePage from './pages/FreelancePage';
import OutreachCRMPage from './pages/OutreachCRMPage';
import SearchPage from './pages/SearchPage';
import AboutPage from './pages/AboutPage';
import ShariaCompliancePage from './pages/ShariaCompliancePage';
import { PublicCustomerProfilePage } from './pages/PublicCustomerProfilePage';
import { PublicPassportPage } from './pages/PublicPassportPage';
import { PassportDashboardPage } from './pages/PassportDashboardPage';
import BusinessAnalyticsPage from './pages/BusinessAnalyticsPage';
import ShopifyAppBridge from './pages/ShopifyAppBridge';
import LoanDashboard from './pages/LoanDashboard';

import AccountManagerDashboard from './pages/AccountManagerDashboard';
