import { Connection, PublicKey, Transaction } from '@solana/web3.js';
import axios from 'axios';

export interface EscrowConfig {
  apiKey: string;
  environment?: 'mainnet' | 'devnet' | 'localnet';
  apiUrl?: string;
}

export interface CreateEscrowParams {
  businessId: string;
  amount: number;
  currency?: string;
  buyerWallet: string;
  escrowTerms?: Record<string, any>;
  successUrl: string;
  cancelUrl: string;
}

export interface Milestone {
  id: string;
  description: string;
  amount: number;
}

export interface CreateMilestoneEscrowParams extends CreateEscrowParams {
  milestones: Milestone[];
}

export interface OracleSignResponse {
  success: boolean;
  data?: {
    signedTxBase64: string;
  };
  error?: string;
}

/**
 * Pabandi Escrow-as-a-Service (EaaS) SDK
 * 
 * Enables third-party developers, marketplaces, and platforms to integrate
 * Pabandi's dynamic, risk-priced, trust-driven escrow protocol.
 */
export class PabandiEscrow {
  private apiKey: string;
  private apiUrl: string;
  private connection: Connection;

  constructor(config: EscrowConfig) {
    this.apiKey = config.apiKey;
    this.apiUrl = config.apiUrl || (
      config.environment === 'mainnet' ? 'https://api.pabandi.com/v1' : 'http://localhost:3000/api/v1'
    );
    
    const rpcUrl = config.environment === 'mainnet' 
      ? 'https://api.mainnet-beta.solana.com' 
      : 'http://127.0.0.1:8899';
    
    this.connection = new Connection(rpcUrl, 'confirmed');
  }

  /**
   * Initializes a new escrow session on the Pabandi backend.
   * This generates the transaction but does NOT broadcast it.
   * The transaction must be signed by the Oracle and the Buyer.
   */
  public async createEscrowSession(params: CreateEscrowParams) {
    const response = await axios.post(`${this.apiUrl}/checkout`, {
      ...params,
      source: 'eaas_sdk'
    }, {
      headers: {
        'Authorization': `Bearer ${this.apiKey}`,
        'Content-Type': 'application/json'
      }
    });

    return response.data;
  }

  /**
   * Initializes a new milestone-based escrow session on the Pabandi backend.
   * Perfect for Freelance Platforms (e.g. Hyve, DeeLance).
   */
  public async createMilestoneEscrow(params: CreateMilestoneEscrowParams) {
    const response = await axios.post(`${this.apiUrl}/checkout/milestone`, {
      ...params,
      source: 'eaas_sdk_freelance'
    }, {
      headers: {
        'Authorization': `Bearer ${this.apiKey}`,
        'Content-Type': 'application/json'
      }
    });

    return response.data;
  }

  /**
   * Fetches the trust/reliability score of a given wallet or business ID.
   * Perfect for Insurance Protocols (e.g. Nexus Mutual) to price premiums
   * for no-shows or default risk dynamically.
   * 
   * @param targetId The Business ID or Wallet Address.
   */
  public async getTrustScoreQuote(targetId: string) {
    try {
      const response = await axios.get(`${this.apiUrl}/trust/quote/${targetId}`, {
        headers: {
          'Authorization': `Bearer ${this.apiKey}`
        }
      });
      return response.data;
    } catch (error: any) {
      throw new Error(error.response?.data?.error || 'Failed to fetch trust score quote');
    }
  }

  /**
   * Requests a signature from the Pabandi Trust Oracle.
   * The Oracle will calculate the buyer's trust score, determine the risk tier,
   * adjust the required deposit accordingly, and co-sign the transaction.
   * 
   * @param serializedTxBase64 The base64 encoded transaction generated by the smart contract.
   * @param customerWallet The public key of the buyer.
   * @returns A base64 encoded transaction containing the Oracle's signature.
   */
  public async requestOracleSignature(serializedTxBase64: string, customerWallet: string): Promise<OracleSignResponse> {
    try {
      const response = await axios.post(`${this.apiUrl}/escrow/sign-init-tx`, {
        serializedTxBase64,
        customerWallet
      }, {
        headers: {
          'Authorization': `Bearer ${this.apiKey}`,
          'Content-Type': 'application/json'
        }
      });
      return response.data;
    } catch (error: any) {
      throw new Error(error.response?.data?.error || 'Failed to request Oracle signature');
    }
  }

  /**
   * Helper utility to deserialize a base64 transaction string back into a Solana Transaction object,
   * which can then be passed to a wallet provider (like Phantom) for the final user signature.
   */
  public deserializeTransaction(base64Tx: string): Transaction {
    const buffer = Buffer.from(base64Tx, 'base64');
    return Transaction.from(buffer);
  }
}
