/**
 * Solana Escrow SDK — Constants
 * ─────────────────────────────────────────────
 * Shared constants for the on-chain escrow program.
 */

// USDC mint addresses
export const USDC_MINT_MAINNET = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v';
export const USDC_MINT_DEVNET = '4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU';

// Program ID — loaded from environment variable
export const PROGRAM_ID = process.env.PABANDI_ESCROW_PROGRAM_ID || '11111111111111111111111111111111';

// Platform fee: 1% (100 basis points)
export const PLATFORM_FEE_BPS = 100;

// Solana RPC URL — loaded from environment
export const RPC_URL = process.env.SOLANA_RPC_URL || 'https://api.devnet.solana.com';

// Escrow program instruction discriminators (keccak-256 first 8 bytes)
// In production, these are generated by Anchor and found in the IDL.
export const INSTRUCTION_DISCRIMINATORS = {
  createEscrow: Buffer.from([0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]),
  fundEscrow: Buffer.from([0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]),
  releaseFunds: Buffer.from([0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]),
  refundFunds: Buffer.from([0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]),
  raiseDispute: Buffer.from([0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]),
};

// Status constants matching the on-chain enum
export const ESCROW_STATUS = {
  CREATED: 'CREATED',
  FUNDED: 'FUNDED',
  RELEASED: 'RELEASED',
  REFUNDED: 'REFUNDED',
  DISPUTED: 'DISPUTED',
} as const;

export type EscrowStatusString = typeof ESCROW_STATUS[keyof typeof ESCROW_STATUS];
