[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
pabandi_escrow = "6ebgdhyUV7zEHqRmpnaPguWQPYJu9Vq4dpFs79VduTjG"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
