import {
  Connection,
  Keypair,
  PublicKey,
  VersionedTransaction,
} from '@solana/web3.js';
import { getAssociatedTokenAddressSync } from '@solana/spl-token';
import * as anchor from '@coral-xyz/anchor';
import { prisma } from '../utils/database';
import { logger } from '../utils/logger';
import IDL from '../utils/pabandi_escrow.json';

const PROGRAM_ID = new PublicKey('6ebgdhyUV7zEHqRmpnaPguWQPYJu9Vq4dpFs79VduTjG');
const TREASURY_WALLET = new PublicKey(process.env.PABANDI_TREASURY_WALLET || 'F5W934e6qJb8z2GZJj3kGjUfN6xLqK4W7CpHbBvRmN3D');

// Load Oracle Keypair securely from env
// This is the Tier 1 Attestation Oracle
const ORACLE_SECRET_KEY = process.env.SOLANA_ORACLE_SECRET_KEY;
let oracleKeypair: Keypair | null = null;
if (ORACLE_SECRET_KEY) {
  oracleKeypair = Keypair.fromSecretKey(
    new Uint8Array(JSON.parse(ORACLE_SECRET_KEY))
  );
}

if (!oracleKeypair) {
  logger.warn(
    '[SolanaEscrow] SOLANA_ORACLE_SECRET_KEY is not configured. ' +
    'Oracle signing operations (initialize_escrow, release_escrow, refund_escrow) ' +
    'will throw at runtime. Set the env var to enable on-chain escrow flows.'
  );
}

const connection = new Connection(
  process.env.SOLANA_RPC_URL || 'https://api.devnet.solana.com',
  'confirmed'
);

const provider = new anchor.AnchorProvider(connection, new anchor.Wallet(oracleKeypair || Keypair.generate()), { commitment: 'confirmed' });
const program = new anchor.Program(IDL as anchor.Idl, provider);

export const solanaEscrowService = {
  /**
   * Partially signs the `initialize_escrow` transaction generated by the frontend.
   * This acts as the Tier 1 Signed Attestation Oracle, approving the trust score and terms.
   */
  async signInitializeEscrowTx(
    serializedTxBase64: string,
    customerWallet: string
  ): Promise<string> {
    if (!oracleKeypair) {
      throw new Error('Oracle Keypair not configured on backend.');
    }

    const txBuffer = Buffer.from(serializedTxBase64, 'base64');
    let transaction: VersionedTransaction;
    try {
      transaction = VersionedTransaction.deserialize(txBuffer);
    } catch (e) {
      throw new Error('Invalid serialized transaction');
    }

    // Deeply inspect the transaction instructions to prevent blind signing.
    // The transaction should only contain the 'initializeEscrow' instruction
    // directed at PROGRAM_ID, with the correct discriminator bytes.
    const message = transaction.message;
    const programIdIndex = message.staticAccountKeys.findIndex(k => k.equals(PROGRAM_ID));

    if (programIdIndex === -1) {
      throw new Error('Transaction does not interact with the expected Program ID.');
    }

    // initialize_escrow discriminator from IDL: [243,160,77,153,11,92,48,209]
    const INITIALIZE_ESCROW_DISCRIMINATOR = new Uint8Array([
      243, 160, 77, 153, 11, 92, 48, 209,
    ]);

    let validInitializeInstructionCount = 0;

    for (const ix of message.compiledInstructions) {
      if (ix.programIdIndex === programIdIndex) {
        // Check that this instruction's data starts with the correct discriminator
        const data = ix.data;
        if (data.length >= INITIALIZE_ESCROW_DISCRIMINATOR.length) {
          let discriminatorMatches = true;
          for (let i = 0; i < INITIALIZE_ESCROW_DISCRIMINATOR.length; i++) {
            if (data[i] !== INITIALIZE_ESCROW_DISCRIMINATOR[i]) {
              discriminatorMatches = false;
              break;
            }
          }
          if (discriminatorMatches) {
            validInitializeInstructionCount++;
          }
        }
      }
    }

    if (validInitializeInstructionCount === 0) {
      throw new Error('No initialize_escrow instruction with valid discriminator found for the Program.');
    }

    // 1. Fetch real-time trust score for this customer
    const user = await prisma.user.findUnique({
      where: { walletAddress: customerWallet }
    });
    if (!user) {
      throw new Error(`Oracle user not registered for wallet: ${customerWallet}`);
    }

    // Sign with the Oracle key
    transaction.sign([oracleKeypair]);

    // Return the partially signed Tx back to frontend for the user to sign and submit
    return Buffer.from(transaction.serialize()).toString('base64');
  },

  /**
   * Oracle-Triggered Release (e.g. from a PMS Webhook or WhatsApp 'Reply Yes' flow)
   */
  async triggerReleaseEscrow(
    reservationId: string,
    customerWalletStr: string,
    businessWalletStr: string,
    mintAddressStr: string
  ): Promise<string> {
    if (!oracleKeypair) {
      throw new Error('Oracle Keypair not configured on backend.');
    }

    const customerWallet = new PublicKey(customerWalletStr);
    const businessWallet = new PublicKey(businessWalletStr);
    const mintAddress = new PublicKey(mintAddressStr);

    // Derive PDAs
    const [escrowStatePDA] = PublicKey.findProgramAddressSync(
      [
        Buffer.from('escrow_state'),
        Buffer.from(reservationId),
        customerWallet.toBuffer(),
      ],
      PROGRAM_ID
    );

    const [vaultTokenPDA] = PublicKey.findProgramAddressSync(
      [
        Buffer.from('escrow_vault'),
        Buffer.from(reservationId),
        customerWallet.toBuffer(),
      ],
      PROGRAM_ID
    );

    const businessTokenAccount = getAssociatedTokenAddressSync(mintAddress, businessWallet);
    const treasuryTokenAccount = getAssociatedTokenAddressSync(mintAddress, TREASURY_WALLET);

    logger.info(`[Escrow Oracle] Triggering Release for ${reservationId}...`);

    try {
      const tx = await program.methods.releaseEscrow()
        .accounts({
          oracleTrigger: oracleKeypair.publicKey,
          escrowState: escrowStatePDA,
          vaultTokenAccount: vaultTokenPDA,
          businessTokenAccount: businessTokenAccount,
          treasuryTokenAccount: treasuryTokenAccount,
        })
        .signers([oracleKeypair])
        .rpc();
        
      logger.info(`[Escrow Oracle] Released funds. Tx: ${tx}`);
      return tx;
    } catch (err: any) {
      logger.error(`[Escrow Oracle] Release failed: ${err.message}`);
      throw new Error(`Release failed: ${err.message}`);
    }
  },

  /**
   * Builds a refund transaction for the customer to sign and submit.
   *
   * The on-chain `refund_escrow` instruction (lib.rs:154) requires the customer
   * to be a signer — the backend cannot refund on the customer's behalf. This
   * function prepares the serialized transaction; the frontend must deserialize,
   * sign with the customer's wallet, and submit to the network.
   *
   * @returns base64-encoded serialized Transaction ready for customer signing
   * @throws if the escrow state PDA doesn't exist or the build fails
   */
  async triggerRefundEscrow(
    reservationId: string,
    customerWalletStr: string,
    mintAddressStr: string
  ): Promise<string> {
    if (!oracleKeypair) {
      throw new Error('Oracle Keypair not configured on backend.');
    }

    const customerWallet = new PublicKey(customerWalletStr);
    const mintAddress = new PublicKey(mintAddressStr);

    // Derive PDAs
    const [escrowStatePDA] = PublicKey.findProgramAddressSync(
      [
        Buffer.from('escrow_state'),
        Buffer.from(reservationId),
        customerWallet.toBuffer(),
      ],
      PROGRAM_ID
    );

    const [vaultTokenPDA] = PublicKey.findProgramAddressSync(
      [
        Buffer.from('escrow_vault'),
        Buffer.from(reservationId),
        customerWallet.toBuffer(),
      ],
      PROGRAM_ID
    );

    const customerTokenAccount = getAssociatedTokenAddressSync(mintAddress, customerWallet);

    logger.info(`[Escrow Oracle] Building refund tx for ${reservationId} (customer must sign)...`);

    try {
      // Build the refund instruction via Anchor.
      // The `customer` account is marked as Signer<'info> in the IDL —
      // the transaction is built with the customer as the required signer,
      // but we do NOT sign here. The customer signs on the frontend.
      const tx = await program.methods.refundEscrow()
        .accounts({
          customer: customerWallet,
          escrowState: escrowStatePDA,
          vaultTokenAccount: vaultTokenPDA,
          customerTokenAccount: customerTokenAccount,
        })
        .transaction();

      // Serialize the Transaction to base64 for the frontend.
      // Frontend flow: Transaction.from(Buffer.from(base64, 'base64'))
      // → tx.sign(customerKeypair) → sendAndConfirmTransaction(connection, tx)
      const serialized = Buffer.from(tx.serialize()).toString('base64');

      logger.info(`[Escrow Oracle] Refund tx prepared for ${reservationId}. Customer must sign and submit.`);
      return serialized;
    } catch (err: any) {
      logger.error(`[Escrow Oracle] Refund tx build failed for ${reservationId}: ${err.message}`);
      throw new Error(`Refund tx preparation failed: ${err.message}`);
    }
  }
};
