import {
  Connection,
  Keypair,
  PublicKey,
  Transaction,
  VersionedTransaction,
} from '@solana/web3.js';
import * as anchor from '@coral-xyz/anchor';
import { trustScoreService } from './trustScore.service';
import { prisma } from '../utils/database';

const PROGRAM_ID = new PublicKey('6ebgdhyUV7zEHqRmpnaPguWQPYJu9Vq4dpFs79VduTjG');

// Load Oracle Keypair securely from env
// This is the Tier 1 Attestation Oracle
const ORACLE_SECRET_KEY = process.env.SOLANA_ORACLE_SECRET_KEY;
let oracleKeypair: Keypair | null = null;
if (ORACLE_SECRET_KEY) {
  oracleKeypair = Keypair.fromSecretKey(
    new Uint8Array(JSON.parse(ORACLE_SECRET_KEY))
  );
}

const connection = new Connection(
  process.env.SOLANA_RPC_URL || 'https://api.devnet.solana.com',
  'confirmed'
);

export const solanaEscrowService = {
  /**
   * Partially signs the `initialize_escrow` transaction generated by the frontend.
   * This acts as the Tier 1 Signed Attestation Oracle, approving the trust score and terms.
   */
  async signInitializeEscrowTx(
    serializedTxBase64: string,
    customerWallet: string
  ): Promise<string> {
    if (!oracleKeypair) {
      throw new Error('Oracle Keypair not configured on backend.');
    }

    const txBuffer = Buffer.from(serializedTxBase64, 'base64');
    let transaction: VersionedTransaction;
    try {
      transaction = VersionedTransaction.deserialize(txBuffer);
    } catch (e) {
      throw new Error('Invalid serialized transaction');
    }

    // In a production environment, we would deeply inspect `transaction.message.instructions`
    // to verify that it is calling the correct `initialize_escrow` instruction on our PROGRAM_ID,
    // and that the parameters (total_amount, etc.) match our database records for this booking.

    // 1. Fetch real-time trust score for this customer
    const user = await prisma.user.findUnique({
      where: { walletAddress: customerWallet }
    });
    const trustScore = user ? user.trustScore : 50.0; // Default to 50 if user not registered

    // (Verification logic goes here to ensure the Tx embeds this correct trustScore)
    // For V1 prototype, we assume the frontend sent the correct Ix and we just sign.

    // Sign with the Oracle key
    transaction.sign([oracleKeypair]);

    // Return the partially signed Tx back to frontend for the user to sign and submit
    return Buffer.from(transaction.serialize()).toString('base64');
  },

  /**
   * Oracle-Triggered Release (e.g. from a PMS Webhook or WhatsApp 'Reply Yes' flow)
   */
  async triggerReleaseEscrow(
    reservationId: string,
    customerWalletStr: string,
    businessWalletStr: string,
    mintAddressStr: string
  ): Promise<string> {
    if (!oracleKeypair) {
      throw new Error('Oracle Keypair not configured on backend.');
    }

    const customerWallet = new PublicKey(customerWalletStr);
    const businessWallet = new PublicKey(businessWalletStr);
    const mintAddress = new PublicKey(mintAddressStr);

    // Derive PDAs
    const [escrowStatePDA] = PublicKey.findProgramAddressSync(
      [
        Buffer.from('escrow_state'),
        Buffer.from(reservationId),
        customerWallet.toBuffer(),
      ],
      PROGRAM_ID
    );

    const [vaultTokenPDA] = PublicKey.findProgramAddressSync(
      [
        Buffer.from('escrow_vault'),
        Buffer.from(reservationId),
        customerWallet.toBuffer(),
      ],
      PROGRAM_ID
    );

    // Derive ATAs (Associated Token Accounts)
    // Assuming ATAs exist for business and treasury
    const treasuryWallet = new PublicKey(
      process.env.PABANDI_TREASURY_WALLET || oracleKeypair.publicKey.toString()
    );

    // Note: Since we are using @coral-xyz/anchor on the backend, we would ideally load the IDL.
    // For this prototype, we outline the connection. The frontend or a simple IDL fetch handles the raw Ix.
    
    // ... Anchor program interaction to call `release_escrow`
    // The Oracle Signs the transaction as `oracle_trigger`.

    return 'tx_signature_mock'; 
  }
};
