import {
  Connection,
  Keypair,
  LAMPORTS_PER_SOL,
} from "@solana/web3.js";
import {
  createMint,
  getOrCreateAssociatedTokenAccount,
  mintTo,
  setAuthority,
  AuthorityType,
} from "@solana/spl-token";
import * as fs from "fs";
import * as path from "path";
import bs58 from "bs58";
import dotenv from "dotenv";

dotenv.config();

const connection = new Connection("https://api.devnet.solana.com", "confirmed");

// Constants
const TOKEN_DECIMALS = 9;
const MAX_SUPPLY = 1_000_000_000 * 10 ** TOKEN_DECIMALS; // 1 Billion

async function main() {
  console.log("🚀 Starting Solana PAB Token Deployment...");

  let payer: Keypair;
  
  if (process.env.SOLANA_PRIVATE_KEY) {
    payer = Keypair.fromSecretKey(bs58.decode(process.env.SOLANA_PRIVATE_KEY));
    console.log("✅ Loaded payer from SOLANA_PRIVATE_KEY.");
  } else {
    payer = Keypair.generate();
    console.log("⚠️ No SOLANA_PRIVATE_KEY found. Generated a new local keypair.");
    console.log(`🔑 Private Key (save this!): ${bs58.encode(payer.secretKey)}`);
    console.log(`👛 Public Key: ${payer.publicKey.toBase58()}`);
    
    // Attempt to fund it
    try {
      console.log("🪂 Requesting airdrop of 2 SOL...");
      const signature = await connection.requestAirdrop(payer.publicKey, 2 * LAMPORTS_PER_SOL);
      await connection.confirmTransaction(signature, "confirmed");
      console.log("✅ Airdrop successful!");
    } catch (e) {
      console.error("❌ Airdrop failed. Please fund the wallet manually at: https://faucet.solana.com/");
      console.log(`Wallet address: ${payer.publicKey.toBase58()}`);
      return;
    }
  }

  const balance = await connection.getBalance(payer.publicKey);
  console.log(`💰 Payer Balance: ${balance / LAMPORTS_PER_SOL} SOL`);

  if (balance < 0.1 * LAMPORTS_PER_SOL) {
      console.error("❌ Insufficient SOL. Please fund the wallet.");
      return;
  }

  console.log("\n📄 Creating Token Mint...");
  // 1. Create Mint
  const mintAddress = await createMint(
    connection,
    payer,              // payer
    payer.publicKey,    // mintAuthority
    payer.publicKey,    // freezeAuthority
    TOKEN_DECIMALS      // decimals
  );

  console.log(`✅ Token Mint created: ${mintAddress.toBase58()}`);

  // 2. Create Associated Token Account for Payer
  console.log("\n🏦 Creating Associated Token Account (ATA) for payer...");
  const tokenAccount = await getOrCreateAssociatedTokenAccount(
    connection,
    payer,
    mintAddress,
    payer.publicKey
  );

  console.log(`✅ Payer ATA: ${tokenAccount.address.toBase58()}`);

  // 3. Mint Initial Supply
  console.log(`\n💎 Minting initial supply of 1 Billion PAB...`);
  await mintTo(
    connection,
    payer,
    mintAddress,
    tokenAccount.address,
    payer, // mintAuthority
    MAX_SUPPLY
  );

  console.log(`✅ Minted 1,000,000,000 tokens to ${tokenAccount.address.toBase58()}`);

  // Save the config to .env.contracts
  const envContent = [
    `# Auto-generated by deploy-pab-solana.ts — ${new Date().toISOString()}`,
    `SOLANA_PAB_MINT_ADDRESS=${mintAddress.toBase58()}`,
    `SOLANA_TREASURY_ACCOUNT=${tokenAccount.address.toBase58()}`,
  ].join("\n");

  const envFile = path.join(__dirname, "../.env.contracts");
  fs.appendFileSync(envFile, "\n" + envContent + "\n");
  console.log(`\n💾 Saved mint address to ${envFile}`);

  console.log("\n🎉 Solana PAB Token Deployment Complete!");
  console.log(`Mint Address: ${mintAddress.toBase58()}`);
  console.log(`You can view this token on Solana Explorer: https://explorer.solana.com/address/${mintAddress.toBase58()}?cluster=devnet`);
}

main().catch(console.error);
