#!/usr/bin/env npx tsx
/**
 * sync-agent-docs.ts — regenerate every machine-readable agent manifest from
 * the live server code, so llms.txt and server.json can never advertise a tool
 * that tools/list does not return.
 *
 * Run: npm run sync:agent-docs
 * Then: npm run verify:agent-surface   (fails if anything is left inconsistent)
 */
import fs from 'fs';
import path from 'path';
import { TOOLS } from '../src/mcp/pabandiMcpServer';
import { pabandiToolsRegistry } from '../src/services/pabandiTools.service';

const ROOT = path.join(__dirname, '..', '..');
const read = (p: string) => fs.readFileSync(path.join(ROOT, p), 'utf8');
const write = (p: string, s: string) => fs.writeFileSync(path.join(ROOT, p), s);

const registryByName = new Map<string, any>(pabandiToolsRegistry.map((t: any) => [t.name, t]));
const byMcpName = new Map<string, any>(pabandiToolsRegistry.map((t: any) => [t.mcpName, t]));

const X402_PRICED = new Set(['pabandi_issue_passport', 'pabandi_initiate_escrow', 'pabandi_create_booking']);

const oneLine = (s: string) => s.replace(/\s+/g, ' ').trim();

function describe(name: string): string {
  const t = byMcpName.get(name);
  if (t) return oneLine(t.short) + (t.exclusiveNote ? ` ${oneLine(t.exclusiveNote)}` : '');
  const engine: Record<string, string> = {
    pabandi_verify_passport: 'Verify a PTP trust attestation (offline-verifiable HMAC signature)',
    pabandi_discover: 'PTP protocol discovery document',
    pabandi_get_ledger: 'Public audit lookup of a passport issuance charge by idempotency key',
    pabandi_discover_platform: 'Full platform capability manifest',
    pabandi_platform_access: 'Grant or inspect an exclusive platform access credential',
  };
  return engine[name] ?? 'See /api/v1/pabandi/tools';
}

function accessLabel(name: string): string {
  const t = byMcpName.get(name);
  if (t) return t.access;
  if (X402_PRICED.has(name)) return 'x402 paid';
  if (name === 'pabandi_verify_passport' || name === 'pabandi_discover' || name === 'pabandi_get_ledger') return 'public';
  return 'auth';
}

// ── llms.txt tool table ───────────────────────────────────────────────────────
const BEGIN = '<!-- BEGIN GENERATED TOOLS -->';
const END = '<!-- END GENERATED TOOLS -->';

const rows = [
  '| Tool | What it does | Access | HTTP equivalent |',
  '|------|--------------|--------|-----------------|',
  ...(TOOLS as any[]).map((t) => {
    const reg = byMcpName.get(t.name);
    const http = reg?.endpoints?.map((e: any) => `\`${e.method} ${e.path}\``).join(', ') ?? '`POST /mcp` (tools/call)';
    return `| \`${t.name}\` | ${describe(t.name)} | ${accessLabel(t.name)} | ${http} |`;
  }),
];

const table = [BEGIN, '<!-- Generated by server/scripts/sync-agent-docs.ts — do not edit by hand -->', '', ...rows, END].join('\n');

const llms = read('llms.txt');
if (!llms.includes(BEGIN)) throw new Error('llms.txt is missing the GENERATED TOOLS markers');
write('llms.txt', llms.slice(0, llms.indexOf(BEGIN)) + table + llms.slice(llms.indexOf(END) + END.length));

// ── server.json manifest ─────────────────────────────────────────────────────
const serverJson = JSON.parse(read('server.json'));
serverJson.tools = (TOOLS as any[]).map((t) => {
  const reg = byMcpName.get(t.name);
  return {
    name: t.name,
    description: describe(t.name),
    ...(X402_PRICED.has(t.name) ? { payment: 'x402' } : {}),
    ...(reg?.access && reg.access !== 'public' ? { access: reg.access } : {}),
  };
});
write('server.json', JSON.stringify(serverJson, null, 2) + '\n');

console.log(`synced ${(TOOLS as any[]).length} tools into llms.txt and server.json`);
for (const [mcpName, reg] of registryByName) {
  if (!mcpName) console.warn(`NOTE  registry entry ${reg.name} has no mcpName`);
}
